# Generated by Django 5.0.4 on 2024-05-29 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_outline_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='subject',
            new_name='schoolYear',
        ),
    ]
