# Generated by Django 5.0.4 on 2024-05-29 16:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_outline_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='outline',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
