# Generated by Django 5.0.4 on 2024-05-31 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_course_description_alter_outline_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
    ]
