# Generated by Django 5.0.4 on 2024-06-01 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_alter_course_image_alter_outline_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('outline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.outline')),
            ],
        ),
    ]
