# Generated by Django 5.0.4 on 2024-06-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='type',
            field=models.CharField(default='default_type', max_length=100),
        ),
    ]
