# Generated by Django 5.0.4 on 2024-06-01 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_alter_point_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='outline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.outline'),
        ),
    ]
