# Generated by Django 5.0.4 on 2024-06-01 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_alter_point_outline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point',
            old_name='score',
            new_name='percent',
        ),
    ]
