# Generated by Django 5.0.4 on 2024-06-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_remove_outline_course_course_outlines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='outlines',
            field=models.ManyToManyField(blank=True, null=True, related_name='courses', to='course.outline'),
        ),
    ]
