# Generated by Django 5.0.4 on 2024-06-02 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_course_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
    ]
