# Generated by Django 5.0.4 on 2024-06-02 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0019_remove_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='outline',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.course'),
        ),
    ]
