# Generated by Django 5.0.4 on 2024-06-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0020_outline_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outline',
            name='course',
        ),
        migrations.AddField(
            model_name='outline',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='outline_set', to='course.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='outlines',
            field=models.ManyToManyField(blank=True, related_name='courses_included', to='course.outline'),
        ),
    ]
